### ISSUE TITLE
default reply topic risks to create control loops

### ISSUE THREAD

**Issue by relet** [perbu/whippet#1]
Defaulting to the sender topic risks to create control loops in the addressed service. 
Any service that replies to (malformed) incoming messages will address itself. 

That needs to be addressed in the service of course, because it's instant DOS, but whippet should not default to that behavior.

**Comment by perbu** [comment]
https://github.com/perbu/whippet/blob/main/whippet/whippet.go#L174C1-L176C3

It does not default to the sender topic.
